/**
 * Worker environment bindings, shared between src/index.ts and src/auth/.
 * (Cloudflare's reference relies on a global `Env` generated by
 * `wrangler types`; this repo doesn't run that step, so it's a plain
 * exported interface instead.)
 */
export interface Env {
    MCP_OBJECT: DurableObjectNamespace;
    /** Nightly project-snapshot backups — see src/backup.ts. */
    BACKUPS: R2Bucket;
    /** OAuth state + client-approval storage for @cloudflare/workers-oauth-provider. */
    OAUTH_KV: KVNamespace;
    GITHUB_CLIENT_ID: string;
    GITHUB_CLIENT_SECRET: string;
    /** HMAC secret for signing the client-approval cookie. */
    COOKIE_ENCRYPTION_KEY: string;
    // Phase 4, after the real LK client ships: LK_API_KEY: string; LK_PROJECT_ID: string;
}
